### ISSUE TITLE
[BUG] missing messages / rooms stop refreshing

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1385]
- Your Rocket.Chat Experimental app version: 4.0.4 and 4.0.5
- Your Rocket.Chat server version: 2.1.1, 2.2.0
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10), BQ Auqaris X5 Plus (Android 7.7.1)

Sometimes is happens that rooms on the Andriod App (version 4.0.4/4.0.5) are not updated anymore or that messages are missing. The process is difficult to replicate, but I have personally seen twice one different smart phones that I get a push notification and when I then enter the channel, the message is not visible there. Other users also report this to me from their devices, that rooms stop showing new messages on the app. The message is displayed in the browser and in the desktop client. So I think it's an app problem.

The problem first arose on 25 October. I see a channel on my replacement device that hasn't updated since October 25th, although I also installed the new 4.0.5 version there today.

In this case it only helps to uninstall the app or delete the cache and the memory contents.

Missing message:
![grafik](https://user-images.githubusercontent.com/8544984/68872410-4a865980-06fe-11ea-8e19-36ccc2064ab4.png)

The missing message comes up after reinstallation:
![grafik](https://user-images.githubusercontent.com/8544984/68871952-879e1c00-06fd-11ea-8fb2-9981f56b221d.png)

Logs:
- no errors in rocket logs on server

**Comment by diegolmello** [comment]
@localguru If you logout and login again, your local database will be deleted and the error will be gone.
If after this process you find more missing content, please let me know.
Thanks

**Comment by localguru** [comment]
@diegolmello FYI: I use only SAML login. Yes, if I logout and login  on SAML again, the rooms are refreshed and up to date. But what does that mean technically? What should that fix?

But would you please reopen the ticket again, because the error here on my device already occurred twice and I do not see a manual logout by the user as a fix, because the user does not know at all that he is missing messages, because a channel is not updated. 

I myself completely uninstalled the app (4.0.4) yesterday and re-registered. Nevertheless, an error occurred in another channel today. In the meantime version 4.0.5 was rolled out. Nevertheless the rooms were not updated today. The problem what exists now is that probably countless users do not notice the problem at all. Should I now tell all users to unsubscribe from the Android app?

**Comment by diegolmello** [comment]
@localguru That's not what I meant. I'm sorry about the confusion.
A fix was released a few weeks ago and until today we were agreeing as fixed.
But that fix wouldn't solve the problem if the message was already missing (only after a logout everything would behave as expected), that's why I asked you to log out and in and keep me updated.

But you said it happened again, so we'll need to investigate further.
I'm reopening the issue.

**Comment by localguru** [comment]
@diegolmello Diego, thanks for you time. Once again to the timeline. Yesterday I noticed on App 4.0.4 that a message was not displayed in a private room, but in my Desktop Cient (2.16.2 on Xubuntu) and in any browser. I deinstalled and reinstalled the app, 4.0.4 again. This included a new login to the Shibboleth IDM. The missing messages in the room were loaded, room up to date. Today I noticed a missing message in another channel, which was posted today, which is after the reinstallation. At least the reinstallation didn't fix the problem, so the problem could come up again. Now I'm on 4.0.5, fresh installation. 
So far I have not informed my users about the phenomenon. As soon as it is noticed, it would damage the confidence in the reliability of the app and the service extremely.

**Comment by localguru** [comment]
@diegolmello the problem is back. This morning some of my rooms didn't refresh on both mobiles. Deleted messages will also continue to be displayed on the app. I have opened two more issues.

**Comment by localguru** [comment]
@diegolmello I've spent hours trying to replicate this annoying problem. I mean it's related to deleting messages and setting the server to `Message/Show Deleted Status` to `False`.

Steps to recreate this:

Test case A:

1. configure `Message/Show Deleted Status` to `False`
2. compare if the last message in a room is current on the app too.
3. turn off the display of the smart phone.
4. write a message "delete me" in this room in the desktop client or in the browser
5. delete this message "delete me" in the desktop client or browser
6. write more messages in the desktop client or browser
7. compare now in the app the actuality of the room.
8. the room on the app does not show any new news, it is still on status in step 2.
9. now, while you are in the room on the app, write a message with the desktop client in that room. This message will now be displayed. The messages from step 6. are not displayed.

Test case B:

Same procedure as in test case A, but `Message/Show Deleted Status` is set to `True`. Now all messages are displayed. Probably the channel is kept in sync because of the `Message removed` status messages.

**Comment by diegolmello** [comment]
@localguru Thanks for your investigation.
We're taking a look and we're going to fix it asap.

**Comment by localguru** [comment]
@diegolmello thank you! The perfidious thing about this behavior is that you don't get any new messages displayed on the app after deleting a message, unless you write a new message yourself or a new message is being written at the time you are in the channel. But if you don't look into the channel for a long time after a message has been deleted, you will miss complete messages.

Probably this behavior also affects the bugs #1391 and #1390.

**Comment by diegolmello** [comment]
@localguru Np.
If you can `Message/Show Deleted Status` to `True` for a while, it would help us.
We need time to release a proper fix.
We're going to work on prune and release it on the same version.

**Comment by localguru** [comment]
@diegolmello no problem, I can activate the feature. Thank you so much for taking care of it.

I was able to replicate the problem as described above on three servers of different versions, so I don't think it's just a problem on my live server. If you want me to test something, just let me know.

**Comment by diegolmello** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/15824 and #1399
