### ISSUE TITLE
ReactOkHttpNetworkFetcher is not public in com.facebook.react.modules.fresco; cannot be accessed from outside package

### ISSUE THREAD

**Issue by glinda93** [RocketChat/Rocket.Chat.ReactNative#3267]
### Description:

I've got this error when I try to run android:

> android/app/src/main/java/chat/airlex/reactnative/networking/SSLPinningModule.java:9: error: ReactOkHttpNetworkFetcher is not public in com.facebook.react.modules.fresco; cannot be accessed from outside package
> 
> import com.facebook.react.modules.fresco.ReactOkHttpNetworkFetcher;

I've inspected `ReactOkHttpNetworkFetcher` class and it's indeed not declared as public.

How can I resolve this error?

### Environment Information:

- Rocket.Chat Server Version: latest
- Rocket.Chat App Version: latest
- Device Name: Android
- OS Version: any

### Steps to reproduce:

1. npx react-native run-android

### Expected behavior:

Should be compiled without error

### Actual behavior:

Throws error

### Additional context:

[SSLPinningModuleCode](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/16fee2aa64fbd2bd358af312909e625da33e1da8/android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java#L9)

[ReactOkHttpNetworkFetcher.java](https://github.com/RocketChat/react-native/blob/3e77e15526def73e54af50e9991c18751bf9aed3/ReactAndroid/src/main/java/com/facebook/react/modules/fresco/ReactOkHttpNetworkFetcher.java#L25)

I wonder how it does work in other dev's environments?

**Comment by jasminehung** [comment]
Same error here with branch:single-server

**Comment by raza2022** [comment]
Strange I am facing the same issue, and linked code didn't change, and the last build finished successfully, @jasminehung @glinda93 have you solved it, or find a workaround, any hint could be very helpful

**Comment by raza2022** [comment]
@diegolmello @djorkaeffalexandre @rodrigok @ggazzo @reinaldonetof @gerzonc my new features can't be pushed due to that issue, what thought it's because some java method is not public, but I didn't found the starting point to make that method public (source File/folder for `com.facebook/xpackage`) any hint will be very helpful

**Comment by anggaprytn** [comment]
same error using rocket chat latest version

**Comment by Shailesh351** [comment]
I'm also facing the same issue

```
/Users/shell/Documents/GitHub/Rocket.Chat.ReactNative/android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java:6: error: cannot find symbol
import com.facebook.react.modules.network.CustomClientBuilder;
                                         ^
  symbol:   class CustomClientBuilder
  location: package com.facebook.react.modules.network
/Users/shell/Documents/GitHub/Rocket.Chat.ReactNative/android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java:9: error: ReactOkHttpNetworkFetcher is not public in com.facebook.react.modules.fresco; cannot be accessed from outside package
import com.facebook.react.modules.fresco.ReactOkHttpNetworkFetcher;
                                        ^
/Users/shell/Documents/GitHub/Rocket.Chat.ReactNative/android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java:50: error: cannot find symbol
    public class CustomClient implements CustomClientBuilder {
                                         ^
  symbol:   class CustomClientBuilder
  location: class SSLPinningModule
/Users/shell/Documents/GitHub/Rocket.Chat.ReactNative/android/app/src/debug/java/chat/rocket/reactnative/ReactNativeFlipper.java:24: error: cannot find symbol
import com.facebook.react.modules.network.CustomClientBuilder;
                                         ^
  symbol:   class CustomClientBuilder
  location: package com.facebook.react.modules.network
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileExperimentalPlayDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by glinda93** [comment]
For more context, this error happens when I tried to upgrade React Native version from `0.63.4` to` 0.64.x` by myself.

Works fine if React Native version is `0.63.4`, although the method is not public.

**Comment by fidelsam1992** [comment]
> For more context, this error happened when I tried to upgrade React Native version from `0.63.4` to` 0.64.x` by myself.
> 
> Works fine if React Native version is `0.63.4`, although the method is not public.

Unfortunately on my side, I didn't change anything on the code and the build fails.

**Comment by glinda93** [comment]
> > For more context, this error happened when I tried to upgrade React Native version from `0.63.4` to` 0.64.x` by myself.
> > Works fine if React Native version is `0.63.4`, although the method is not public.
> 
> Unfortunately on my side, I didn't change anything on the code and the build fails.

What is your React Native version?

**Comment by fidelsam1992** [comment]
> > > For more context, this error happened when I tried to upgrade React Native version from `0.63.4` to` 0.64.x` by myself.
> > > Works fine if React Native version is `0.63.4`, although the method is not public.
> > 
> > 
> > Unfortunately on my side, I didn't change anything on the code and the build fails.
> 
> What is your React Native version?

The one defined in the repo
```
"react-native": "RocketChat/react-native#0.63.4",
```

**Comment by diegolmello** [comment]
For those changing React Native version on package.json and expecting to be enough, it's not :) 
I updated it here and it's merged on develop branch, but not released on single-server branch yet https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3245

Can you all try develop branch just to see if the error is gone?
I went through your error during the update, but it was gone after cleaning everything.
Try this on develop branch
```
rm -rf node_modules
rm -rf android/app/build
yarn
yarn android
```

**Comment by fidelsam1992** [comment]
> For those changing React Native version on package.json and expecting to be enough, it's not :)
> I updated it [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3245) and it's merged on develop branch, but not released on single-server branch yet
> 
> Can you all try develop branch just to see if the error is gone?
> I went through your error during the update, but it was gone after cleaning everything.
> Try this on develop branch
> 
> ```
> rm -rf node_modules
> rm -rf android/app/build
> yarn
> yarn android
> ```

Still fails for me (Without upgrading react-native, my current version is `"react-native": "RocketChat/react-native#0.63.4"`

**Comment by shamsnaamir** [comment]
> > For those changing React Native version on package.json and expecting to be enough, it's not :)
> > I updated it [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3245) and it's merged on develop branch, but not released on single-server branch yet
> > Can you all try develop branch just to see if the error is gone?
> > I went through your error during the update, but it was gone after cleaning everything.
> > Try this on develop branch
> > ```
> > rm -rf node_modules
> > rm -rf android/app/build
> > yarn
> > yarn android
> > ```
> 
> Still fails for me (Without upgrading react-native, my current version is `"react-native": "RocketChat/react-native#0.63.4"`

same

**Comment by anggaprytn** [comment]
> For those changing React Native version on package.json and expecting to be enough, it's not :)
> I updated it [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3245) and it's merged on develop branch, but not released on single-server branch yet
> 
> Can you all try develop branch just to see if the error is gone?
> I went through your error during the update, but it was gone after cleaning everything.
> Try this on develop branch
> 
> ```
> rm -rf node_modules
> rm -rf android/app/build
> yarn
> yarn android
> ```

BUILD SUCCESSFUL using branch develop

**Comment by shamsnaamir** [comment]
> For those changing React Native version on package.json and expecting to be enough, it's not :)
> I updated it [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3245) and it's merged on develop branch, but not released on single-server branch yet
> 
> Can you all try develop branch just to see if the error is gone?
> I went through your error during the update, but it was gone after cleaning everything.
> Try this on develop branch
> 
> ```
> rm -rf node_modules
> rm -rf android/app/build
> yarn
> yarn android
> ```

I cloned develop branch and it compiled successfully. but about  the single-server branch what should I do?
should I change react-native version or something else?
thanks.

**Comment by shamsnaamir** [comment]
I changed react-native version to 0.64.2 and removed the patch file related to react-native-0.63.2 and changed `metro-config/src/defaults/blacklist` to `metro-config/src/defaults/exclusionList` and it compiled SUCCESSFULLY!
but after we login to the workspace this error appears:
```
 ERROR  Error: _c(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

This error is located at:
    in _c (at theme.js:9)
    in ThemedComponent (at RoomItem.js:116)
    in RCTView (at View.js:34)
    in Unknown (at RoomItem.js:106)
    in RCTView (at View.js:34)
    in Unknown (at Wrapper.js:29)
    in RCTView (at View.js:34)
    in Unknown (at Wrapper.js:18)
    in Wrapper (at RoomItem.js:70)
    in RNGestureHandlerButton (at createNativeWrapper.js:80)
    in NativeViewGestureHandler (at createNativeWrapper.js:79)
    in ComponentWrapper (at GestureButtons.js:66)
    in BaseButton (at GestureButtons.js:114)
    in RectButton (at touch.js:22)
    in Touch (at Touchable.js:263)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Touchable.js:258)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Touchable.js:242)
    in PanGestureHandler (at Touchable.js:236)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Touchable.js:235)
    in LongPressGestureHandler (at Touchable.js:234)
    in Touchable (at RoomItem.js:54)
    in RoomItem (at RoomItem/index.js:168)
    in RoomItemContainer (created by ConnectFunction)
    in ConnectFunction (at RoomsListView/index.js:906)
    in RCTView (at View.js:34)
    in Unknown (at VirtualizedList.js:2016)
    in VirtualizedListCellContextProvider (at VirtualizedList.js:2031)
    in CellRenderer (at VirtualizedList.js:808)
    in RCTView (at View.js:34)
    in Unknown (at ScrollView.js:1107)
    in RCTScrollView (at ScrollView.js:1236)
    in AndroidSwipeRefreshLayout (at RefreshControl.js:197)
    in RefreshControl (at RoomsListView/index.js:963)
    in ScrollView (at ScrollView.js:1272)
    in ScrollView (at VirtualizedList.js:1251)
    in VirtualizedListContextProvider (at VirtualizedList.js:1081)
    in VirtualizedList (at FlatList.js:620)
    in FlatList (at RoomsListView/index.js:950)
    in RNCSafeAreaView (at SafeAreaView.js:17)
    in _c (at theme.js:9)
    in ThemedComponent (at RoomsListView/index.js:990)
    in RoomsListView (at SafeAreaContext.tsx:126)
    in Unknown (at theme.js:9)
    in ThemedComponent (at dimensions.js:10)
    in DimensionsComponent (created by ConnectFunction)
    in ConnectFunction (at SceneView.tsx:112)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in Unknown (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:562)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:534)
    in RCTView (at View.js:34)
    in Unknown (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in Unknown (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at InsideStack.js:83)
    in ChatsStackNavigator (at SceneView.tsx:112)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.js:109)
    in Screen (at ResourceSavingScene.tsx:21)
    in ResourceSavingScene (at DrawerView.tsx:169)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at DrawerView.tsx:153)
    in RCTView (at View.js:34)
    in Unknown (at Drawer.tsx:639)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:233)
    in AnimatedComponent(View) (at Drawer.tsx:632)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:233)
    in AnimatedComponent(View) (at Drawer.tsx:622)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Drawer.tsx:613)
    in DrawerView (at DrawerView.tsx:190)
    in SafeAreaProviderCompat (at DrawerView.tsx:188)
    in RCTView (at View.js:34)
    in Unknown (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at DrawerView.tsx:187)
    in DrawerView (at createDrawerNavigator.tsx:44)
    in DrawerNavigator (at InsideStack.js:317)
    in DrawerNavigator (at SceneView.tsx:112)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in Unknown (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:562)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:534)
    in RCTView (at View.js:34)
    in Unknown (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RCTView (at View.js:34)
    in Unknown (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:545)
    in RCTView (at View.js:34)
    in Unknown (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in RCTView (at View.js:34)
    in Unknown (at GestureHandlerRootView.android.js:26)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at InsideStack.js:404)
    in InsideStackNavigator (at SceneView.tsx:112)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:104)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:198)
    in RCTView (at View.js:34)
    in Unknown (at CardContainer.tsx:197)
    in RCTView (at View.js:34)
    in Unknown (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:562)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:538)
    in RCTView (at View.js:34)
    in Unknown (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:534)
    in RCTView (at View.js:34)
    in Unknown (at Card.tsx:528)
    in Card (at CardContainer.tsx:167)
    in CardContainer (at CardStack.tsx:552)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.js:109)
    in Screen (at Screens.tsx:67)
    in MaybeScreen (at CardStack.tsx:545)
    in RNSScreenContainer (at src/index.native.js:134)
    in ScreenContainer (at Screens.tsx:45)
    in MaybeScreenContainer (at CardStack.tsx:455)
    in CardStack (at StackView.tsx:437)
    in KeyboardManager (at StackView.tsx:435)
    in SafeAreaProviderCompat (at StackView.tsx:432)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:431)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at AppContainer.js:66)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:376)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at AppContainer.js:54)
    in Unknown (created by ConnectFunction)
    in ConnectFunction (at app/index.js:224)
    in Unknown
    in Unknown (at app/index.js:223)
    in Provider (at app/index.js:206)
    in RCTView (at View.js:34)
    in Unknown (at NativeAppearance.tsx:4)
    in FallbackAppearanceProvider (at src/index.tsx:70)
    in AppearanceProvider (at app/index.js:205)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at app/index.js:204)
    in Root (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in Unknown (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in Unknown (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40), js engine: hermes
```

**Comment by shamsnaamir** [comment]
> I changed react-native version to 0.64.2 and removed the patch file related to react-native-0.63.2 and changed `metro-config/src/defaults/blacklist` to `metro-config/src/defaults/exclusionList` in `metro.config.js` and it compiled SUCCESSFULLY!
> but after we login to the workspace this error appears:
> 
> ```
>  ERROR  Error: _c(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
> 
> This error is located at:
>     in _c (at theme.js:9)
>     in ThemedComponent (at RoomItem.js:116)
>     in RCTView (at View.js:34)
>     in Unknown (at RoomItem.js:106)
>     in RCTView (at View.js:34)
>     in Unknown (at Wrapper.js:29)
>     in RCTView (at View.js:34)
>     in Unknown (at Wrapper.js:18)
>     in Wrapper (at RoomItem.js:70)
>     in RNGestureHandlerButton (at createNativeWrapper.js:80)
>     in NativeViewGestureHandler (at createNativeWrapper.js:79)
>     in ComponentWrapper (at GestureButtons.js:66)
>     in BaseButton (at GestureButtons.js:114)
>     in RectButton (at touch.js:22)
>     in Touch (at Touchable.js:263)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Touchable.js:258)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Touchable.js:242)
>     in PanGestureHandler (at Touchable.js:236)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Touchable.js:235)
>     in LongPressGestureHandler (at Touchable.js:234)
>     in Touchable (at RoomItem.js:54)
>     in RoomItem (at RoomItem/index.js:168)
>     in RoomItemContainer (created by ConnectFunction)
>     in ConnectFunction (at RoomsListView/index.js:906)
>     in RCTView (at View.js:34)
>     in Unknown (at VirtualizedList.js:2016)
>     in VirtualizedListCellContextProvider (at VirtualizedList.js:2031)
>     in CellRenderer (at VirtualizedList.js:808)
>     in RCTView (at View.js:34)
>     in Unknown (at ScrollView.js:1107)
>     in RCTScrollView (at ScrollView.js:1236)
>     in AndroidSwipeRefreshLayout (at RefreshControl.js:197)
>     in RefreshControl (at RoomsListView/index.js:963)
>     in ScrollView (at ScrollView.js:1272)
>     in ScrollView (at VirtualizedList.js:1251)
>     in VirtualizedListContextProvider (at VirtualizedList.js:1081)
>     in VirtualizedList (at FlatList.js:620)
>     in FlatList (at RoomsListView/index.js:950)
>     in RNCSafeAreaView (at SafeAreaView.js:17)
>     in _c (at theme.js:9)
>     in ThemedComponent (at RoomsListView/index.js:990)
>     in RoomsListView (at SafeAreaContext.tsx:126)
>     in Unknown (at theme.js:9)
>     in ThemedComponent (at dimensions.js:10)
>     in DimensionsComponent (created by ConnectFunction)
>     in ConnectFunction (at SceneView.tsx:112)
>     in StaticContainer
>     in EnsureSingleNavigator (at SceneView.tsx:104)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:198)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:197)
>     in RCTView (at View.js:34)
>     in Unknown (at CardSheet.tsx:33)
>     in CardSheet (at Card.tsx:562)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:544)
>     in PanGestureHandler (at GestureHandler.native.tsx:13)
>     in PanGestureHandler (at Card.tsx:538)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:534)
>     in RCTView (at View.js:34)
>     in Unknown (at Card.tsx:528)
>     in Card (at CardContainer.tsx:167)
>     in CardContainer (at CardStack.tsx:552)
>     in RNSScreen (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at src/index.native.js:109)
>     in Screen (at Screens.tsx:67)
>     in MaybeScreen (at CardStack.tsx:545)
>     in RNSScreenContainer (at src/index.native.js:134)
>     in ScreenContainer (at Screens.tsx:45)
>     in MaybeScreenContainer (at CardStack.tsx:455)
>     in CardStack (at StackView.tsx:437)
>     in KeyboardManager (at StackView.tsx:435)
>     in SafeAreaProviderCompat (at StackView.tsx:432)
>     in RCTView (at View.js:34)
>     in Unknown (at GestureHandlerRootView.android.js:26)
>     in GestureHandlerRootView (at StackView.tsx:431)
>     in StackView (at createStackNavigator.tsx:82)
>     in StackNavigator (at InsideStack.js:83)
>     in ChatsStackNavigator (at SceneView.tsx:112)
>     in StaticContainer
>     in EnsureSingleNavigator (at SceneView.tsx:104)
>     in SceneView (at useDescriptors.tsx:150)
>     in RNSScreen (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at src/index.native.js:109)
>     in Screen (at ResourceSavingScene.tsx:21)
>     in ResourceSavingScene (at DrawerView.tsx:169)
>     in RNSScreenContainer (at src/index.native.js:134)
>     in ScreenContainer (at DrawerView.tsx:153)
>     in RCTView (at View.js:34)
>     in Unknown (at Drawer.tsx:639)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:233)
>     in AnimatedComponent(View) (at Drawer.tsx:632)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:233)
>     in AnimatedComponent(View) (at Drawer.tsx:622)
>     in PanGestureHandler (at GestureHandler.native.tsx:13)
>     in PanGestureHandler (at Drawer.tsx:613)
>     in DrawerView (at DrawerView.tsx:190)
>     in SafeAreaProviderCompat (at DrawerView.tsx:188)
>     in RCTView (at View.js:34)
>     in Unknown (at GestureHandlerRootView.android.js:26)
>     in GestureHandlerRootView (at DrawerView.tsx:187)
>     in DrawerView (at createDrawerNavigator.tsx:44)
>     in DrawerNavigator (at InsideStack.js:317)
>     in DrawerNavigator (at SceneView.tsx:112)
>     in StaticContainer
>     in EnsureSingleNavigator (at SceneView.tsx:104)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:198)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:197)
>     in RCTView (at View.js:34)
>     in Unknown (at CardSheet.tsx:33)
>     in CardSheet (at Card.tsx:562)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:544)
>     in PanGestureHandler (at GestureHandler.native.tsx:13)
>     in PanGestureHandler (at Card.tsx:538)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:534)
>     in RCTView (at View.js:34)
>     in Unknown (at Card.tsx:528)
>     in Card (at CardContainer.tsx:167)
>     in CardContainer (at CardStack.tsx:552)
>     in RCTView (at View.js:34)
>     in Unknown (at Screens.tsx:70)
>     in MaybeScreen (at CardStack.tsx:545)
>     in RCTView (at View.js:34)
>     in Unknown (at Screens.tsx:48)
>     in MaybeScreenContainer (at CardStack.tsx:455)
>     in CardStack (at StackView.tsx:437)
>     in KeyboardManager (at StackView.tsx:435)
>     in SafeAreaProviderCompat (at StackView.tsx:432)
>     in RCTView (at View.js:34)
>     in Unknown (at GestureHandlerRootView.android.js:26)
>     in GestureHandlerRootView (at StackView.tsx:431)
>     in StackView (at createStackNavigator.tsx:82)
>     in StackNavigator (at InsideStack.js:404)
>     in InsideStackNavigator (at SceneView.tsx:112)
>     in StaticContainer
>     in EnsureSingleNavigator (at SceneView.tsx:104)
>     in SceneView (at useDescriptors.tsx:150)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:198)
>     in RCTView (at View.js:34)
>     in Unknown (at CardContainer.tsx:197)
>     in RCTView (at View.js:34)
>     in Unknown (at CardSheet.tsx:33)
>     in CardSheet (at Card.tsx:562)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:544)
>     in PanGestureHandler (at GestureHandler.native.tsx:13)
>     in PanGestureHandler (at Card.tsx:538)
>     in RCTView (at View.js:34)
>     in Unknown (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at Card.tsx:534)
>     in RCTView (at View.js:34)
>     in Unknown (at Card.tsx:528)
>     in Card (at CardContainer.tsx:167)
>     in CardContainer (at CardStack.tsx:552)
>     in RNSScreen (at createAnimatedComponent.js:217)
>     in AnimatedComponent (at createAnimatedComponent.js:278)
>     in AnimatedComponentWrapper (at src/index.native.js:109)
>     in Screen (at Screens.tsx:67)
>     in MaybeScreen (at CardStack.tsx:545)
>     in RNSScreenContainer (at src/index.native.js:134)
>     in ScreenContainer (at Screens.tsx:45)
>     in MaybeScreenContainer (at CardStack.tsx:455)
>     in CardStack (at StackView.tsx:437)
>     in KeyboardManager (at StackView.tsx:435)
>     in SafeAreaProviderCompat (at StackView.tsx:432)
>     in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
>     in GestureHandlerRootView (at StackView.tsx:431)
>     in StackView (at createStackNavigator.tsx:82)
>     in StackNavigator (at AppContainer.js:66)
>     in EnsureSingleNavigator (at BaseNavigationContainer.tsx:376)
>     in BaseNavigationContainer (at NavigationContainer.tsx:91)
>     in ThemeProvider (at NavigationContainer.tsx:90)
>     in NavigationContainer (at AppContainer.js:54)
>     in Unknown (created by ConnectFunction)
>     in ConnectFunction (at app/index.js:224)
>     in Unknown
>     in Unknown (at app/index.js:223)
>     in Provider (at app/index.js:206)
>     in RCTView (at View.js:34)
>     in Unknown (at NativeAppearance.tsx:4)
>     in FallbackAppearanceProvider (at src/index.tsx:70)
>     in AppearanceProvider (at app/index.js:205)
>     in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
>     in SafeAreaProvider (at app/index.js:204)
>     in Root (at renderApplication.js:47)
>     in RCTView (at View.js:34)
>     in Unknown (at AppContainer.js:107)
>     in RCTView (at View.js:34)
>     in Unknown (at AppContainer.js:134)
>     in AppContainer (at renderApplication.js:40), js engine: hermes
> ```

Is this problem solvable? Should I wait until the release on the single-server branch?
Should I copy files from develop branch to the project, which files?
Should I clone the develop branch and change it and make it kinda "single-server"?

**Comment by diegolmello** [comment]
We released 4.19.0 Yesterday https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.19.0
Make sure you pull `single-server`, clean everything and try again.
New version contains several dependencies updates (RN, Jitsi, etc), performance improvements (Hermes on iOS) and bug fixes.
Thank you.

**Comment by ljcp** [comment]
@diegolmello we are facing same issue ( already clean all caches and everything) we are using 4.17.0 version  without doing any change or upgrade to the code now CircleCI is failing , with this same error , so something dependency has to be changed that now doesn't play along with older versions , do you have a clue what could be ?  is upgrading to 4.19.0 the only fix ?

**Comment by ljcp** [comment]
issue is that even we are using 4.17.0 and and react native 0.63.4 , Gradle is grabbing version 0.64.2 , trying to figure out where is that set hmm or how to force to stay in 0.63.4

**Comment by ljcp** [comment]
for those having my same issue , the problem resides in the jitsi-maven-repository , they didn't change the version number and jitsi is requiring 0.64.2 so the whole project gets the 0.64.2 instead of the 0.63.4 from node modules , you just need to fork the jitsi repository and revert back the commit and update the address in the Gradle build file

**Comment by glinda93** [comment]
> for those having my same issue , the problem resides in the jitsi-maven-repository , they didn't change the version number and jitsi is requiring 0.64.2 so the whole project gets the 0.64.2 instead of the 0.63.4 from node modules , you just need to fork the jitsi repository and revert back the commit and update the address in the Gradle build file

Good point.

I've fixed build issue like this:

**android/app/build.gradle**

```
- jitsi_url = "https://github.com/RocketChat/jitsi-maven-repository/raw/master/releases"
+ jitsi_url = "https://github.com/RocketChat/jitsi-maven-repository/tree/9ecd55fba726c728c9a9b0e864b6c79ff09281f4/releases"
```

**Comment by glinda93** [comment]
> for those having my same issue , the problem resides in the jitsi-maven-repository , they didn't change the version number and jitsi is requiring 0.64.2 so the whole project gets the 0.64.2 instead of the 0.63.4 from node modules , you just need to fork the jitsi repository and revert back the commit and update the address in the Gradle build file

This.
I've fixed issue with the following change:

**android/build.gradle**
```
jitsi_url = "https://github.com/RocketChat/jitsi-maven-repository/raw/9ecd55fba726c728c9a9b0e864b6c79ff09281f4/releases"
        jitsi_version = "2.10.2"
```

**Comment by luatvudinh** [comment]
Still happen on Dec 2022. Please let me know the root reason.

**Comment by diegolmello** [comment]
@luatvudinh We're on 4.33.0. Update and try again.

**Comment by luatvudinh** [comment]
> @luatvudinh We're on 4.33.0. Update and try again.

After few days fixing this issue. I realized that it was associated with this huge [Nov 4th issue](https://github.com/facebook/react-native/issues/35210)

The solution is to force react-native version in android project match version in `package.json`, 0.64.+ is mine (only need with react native version less than 0.66.+)
```
allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:0.64.+"
        }
    }

    // current settings...
}
```

Hope this would be helpful.
