### ISSUE TITLE
Push Notification Custom Server Not Working

### ISSUE THREAD

**Issue by masterbater** [RocketChat/Rocket.Chat.ReactNative#367]
Hi @diegolmello 
I edited 	
`<meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="61250997538883\0"/>`

Disabled the default gateway
![screen shot 2018-07-13 at 11 49 15 pm](https://user-images.githubusercontent.com/26339988/42700869-975662c4-86f7-11e8-9853-cccafdb18c97.png)
Added the GCM api and secret
![screen shot 2018-07-13 at 11 50 09 pm](https://user-images.githubusercontent.com/26339988/42700904-b314b95c-86f7-11e8-8e87-0fff20f6935b.png)
It doesn't work i press the SEND A TEST PUSHT TO MY USER. I dont received any notification.
I also tried the experimental release or the android version in play store, input my server, then test out the notification it doesn't work. If i disable the default gateway.

**Comment by masterbater** [comment]
I found the problem, i tried the LocalNotification of react-navigation-push-notifcation wix and there is an error, "Failed to post notification on channel"  I was using android 8 emulator, then i tried it in marshmallow, remote notifications are working.

**Comment by skhizerabass** [comment]
@masterbater  Can you help me in configuring this notification?
I have replaced sender ID in manifest which I got from firebase console.
but I still get this error

`08-01 00:01:52.421 17065-17847/? E/ReactNativeNotifs: Failed to retrieve new token
    java.lang.Exception: FATAL: Failed to fetch a fresh new token, instanceId=d6sC-nfoeGE
        at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:99)
        at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
        at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
        at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.IOException: INVALID_SENDER
        at com.google.android.gms.iid.zzaf.zzi(Unknown Source)
        at com.google.android.gms.iid.InstanceID.zze(Unknown Source)
        at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
        at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
        at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:95)
        at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77) 
        at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66) 
        at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) `


Can you look into this?

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="myapp.chat"
	android:versionCode="1"
	android:versionName="1.0">

	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>

	<permission
		android:name="${applicationId}.permission.C2D_MESSAGE"
		android:protectionLevel="signature" />
	<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

	<application
		android:name=".MainApplication"
		android:allowBackup="true"
		android:label="@string/app_name"
		android:icon="@mipmap/ic_launcher"
		android:theme="@style/AppTheme"
		android:resizeableActivity="true"
		android:largeHeap="true">
		<activity
			android:name=".MainActivity"
			android:label="@string/app_name"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
			android:launchMode="singleTop"
			android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter android:label="RocketChatRN">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https" android:host="go.rocket.chat" />
				<data android:scheme="rocketchat" android:host="room" />
				<data android:scheme="rocketchat" android:host="auth" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

		<meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="122571196223\0"/>
	</application>

</manifest>
`

**Comment by diegolmello** [comment]
@masterbater This Android 8 notification error was fixed in #382 🥇

**Comment by diegolmello** [comment]
@skhizerabass 
> I have replaced sender ID in manifest which I got from firebase console.
We don't support FCM yet. Only GCM.

**Comment by skhizerabass** [comment]
@diegolmello  Yes I know that And this Sender ID is same in GCM too. I double checked that. 
But it is still throwing the same exception and i am not able to send any notification nor i am receiving any. If you can help me in this I will be thankful

**Comment by masterbater** [comment]
@skhizerabass you can try create a firebase project then go to project settings then in messaging tab. it will work for gcm. also check if your android virtual image has play store or google api, also login your google account. I notice i cant recieved notification if i wont login any google account.  In any case check if local notification works. If its compiling issues dont use jdk10 use jdk 8

**Comment by skhizerabass** [comment]
Ok I somehow have created the device token using FCM. But now the problem is I sometimes receive notifications and most of the times I don't receive them. While on my web It is working very smoothly
