### ISSUE TITLE
Unable to upload images from iOS & iPhone Mini 12 

### ISSUE THREAD

**Issue by ckrew89** [RocketChat/Rocket.Chat.ReactNative#3846]
### Environment Information:

- Rocket.Chat Server Version: 4.4
- Rocket.Chat App Version: 4.25.0.29369
- Device Name:  iPhone Mini 12 
- OS Version: 15.3.1

### Steps to reproduce:

1.  Open any chat (Room, DM, note to self, etc) 
2.  Press "+" and "Choose from Library," select any locally stored photo, and press "Done" 
3. Image preview pans to black space below the image preview; you can scroll up to view the preview;
4. No Send button appears. 

### Expected behavior:

1. Steps 1, 2 above should produce a preview center-view, with a Send button. 
2. Image should be sent to the selected chat. 

### Actual behavior:

1. Steps 1,2 does not enable the user to send an image. 

### Additional context:

I have tested this on iPhone 13 Mini w/ iOS 15.x, and tested on an iPad Pro also running the latest available iOS. Both work as expected.  Prior to creation of bug report I have factory-reset the device and reinstalled Rocket.Chat latest from the App Store (did NOT restore app from backup) 

I have cleared local application cache. 

I have attempted different file types, all have the same behavior. \

**Comment by homberger** [comment]
Having this issue on my iPhone SE 2020 and iOS 15.4.1 too.

**Comment by GleidsonDaniel** [comment]
@homberger did you test the latest version?
We released a fix for this issue recently.

**Comment by homberger** [comment]
> @homberger did you test the latest version?

I am unable to connect to any Rocket.Chat server using the latest version of the german AppStore and opened issue #4017

> We released a fix for this issue recently.

I would love to test it :)

**Comment by ckrew89** [comment]
Just to confirm, I verified my local version is 4.26.2, and retested; the issue persists.

**Comment by homberger** [comment]
> did you test the latest version?

After an reinstall of the app I was able to test it again with the latest version 4.26.2.30993 and I was still not able to upload an image to any chat. Even to the official open chat server it does not work. Video attached.

https://user-images.githubusercontent.com/681335/161928500-7685aea1-b20a-4c83-a9c5-c4012ba98269.mov

**Comment by mhaluska** [comment]
Same problem here, tested on iOS and iPadOS 15.4.
Server: open.rocket.chat (4.7)
App version: 4.27.1.32265

https://user-images.githubusercontent.com/6524187/166895668-3dfe6d4b-92a6-4652-ac4c-ba4e85fb8808.mov

**Comment by homberger** [comment]
@diegolmello Do you have a clue what is happening here? This bug is really annoying as it is not possible to send any file with Rocket.Chat on iOS.

Is everyone experiencing this problem on iOS devices or only some users?

**Comment by homberger** [comment]
@GleidsonDaniel
> We released a fix for this issue recently.

Do you have a link to the mentioned fix, pr or the associated issue?

> @homberger did you test the latest version? We released a fix for this issue recently.

**Comment by GleidsonDaniel** [comment]
@homberger can you test something?
Try to send an image via share, in this case opening the photo app and asking to share with the app.
See if it works please.

**Comment by homberger** [comment]
Hi @GleidsonDaniel!

> @homberger can you test something? Try to send an image via share, in this case opening the photo app and asking to share with the app. See if it works please.

This does not work either. The behaviour is the same. :(

**Comment by Docmaru** [comment]
iPhone 11 Pro, iOS 15.1, server version 4.1, White label App based on version 4.26. Same issue =(

**Comment by mhaluska** [comment]
Small change, no more scrolling up required, but still not able to send.

iPadOS 16 Beta 2
Rocket.Chat Beta 4.29.0.33852

https://user-images.githubusercontent.com/6524187/176994643-2598a6c9-0c43-4886-88ce-3b8b47c0b278.MOV

**Comment by Szosiem** [comment]
I found a workaround on iPhone 11 Pro Max iOS 15.4.1
After you select photo to send and got black screen try to rotate phone from vertical to horizontal position. After that you can see on bottom of the screen “Type message” input and send button.

I hope it helped. And note to devs: it’s crucial functionality in that type of app - try to fix that soon…

**Comment by mhaluska** [comment]
@Szosiem doesn't work for me on devices and versions above your comment, same for stable client 4.28. Anyway, thanks for tip 👍

**Comment by homberger** [comment]
Problem still exists :(

**Comment by mhaluska** [comment]
> Problem still exists :(

Yes, except iPad with stage manager enabled, then it’s working fine.

**Comment by reinaldonetof** [comment]
Hello, @homberger, and @mhaluska. I really want to help y'all.

Is the error still happening? I tried to reproduce it with different devices and simulators, and also I requested internal co-workers to reproduce this bug and we aren't able to reproduce it. 

Is there any trick or different option that you noticed using your apps?
If possible, test with the last release. I'm waiting for any news from you.

**Comment by ckrew89** [comment]
I just tried it again (iPhone mini 12) with version 4.34.0.36627 and problem is the same: no send button on the image preview.

**Comment by mhaluska** [comment]
@reinaldonetof App version: 4.34.0.36627 iOS version: 16.2
iPhone -> click plus in landscape and pick photo, then rotate to portrait = I can see send over picture (in the middle), doesn‘
t work in portrait, even rotating to landscape
iPad -> same as iPhone, I tried Stage manager on/off, but still same issue.

**Comment by reinaldonetof** [comment]
Is there a specific image when happening this? Is it only for images?

If you go to the device's gallery, then share the image/file using the button `share` with Rocket.Chat, what happens? (You will notice that the rooms list is different when opening the app, however, the screen to send is the same)

**Comment by homberger** [comment]
Wooohooo! I am able to share ! Finally! 🥳

Settings  -> Accessibility -> Motion

I disabled and then reenabled "Reduce Motion". I also changed the dynamic text size to smaller and then back to default. After that the sharing of images to Rocket.Chat was finally possible. I was not able to change back the settings to any values that would make the problem reappear.

**Comment by mhaluska** [comment]
@homberger Thanks for hint! Reduce Motion can be enabled, problem is caused by Prefer Cross-Fade Transitions. Just disable this and Reduce Motion leave enabled, then sharing is working fine.

**Comment by homberger** [comment]
@mhaluska Yes, you are right, thank you! :)

German translation of the settings option "Prefer Cross-Fade Transitions" is "Überblenden bevorzugen".

**Comment by diegolmello** [comment]
Huge news!!
Awkward behavior though.
We're going to try to reproduce it here in order to work on a fix.

What's the settings we need to configure there in order to do it?
Only enable reduce motion and increase font size?

**Comment by mhaluska** [comment]
@diegolmello 
Reduce Motion + Prefer Cross-Fade Transitions
Prefer Cross-Fade Transitions is causing this trouble.

**Comment by essal0815** [comment]
Are there any news, if this will be fixed. Or is it simply assumed to have Cross-Fade Transitions turned off. If so, it might be helpful to somehow mention it in the app.

**Comment by ljkoning** [comment]
There is another likely related problem when you enable "Prefer Cross-Fade Transitions":

When you are in the chat list (main menu->chats), tap the search icon, search for a name, select the name in the results list. Now no "new message" field appears at the bottom of the screen. So you cannot create a new message in the chat. (Workaround for this is: scroll up, long press any previous message, tap "Quote", remove the quote by tapping the x, and then create your message.)

+1 to support "Prefer Cross-Fade Transitions".

**Comment by schmik** [comment]
> I disabled and then reenabled "Reduce Motion". I also changed the dynamic text size to smaller and then back to default. After that the sharing of images to Rocket.Chat was finally possible. I was not able to change back the settings to any values that would make the problem reappear.

I'm so glad I finally spent some time researching this issue and discovering this "solution". iOS looks kind of new to me now, all this motion, everywhere... But at least I can finally share/take pictures while using mobile, like back in the ICQ-days 😀 

@homberger Thanks for sharing
