### ISSUE TITLE
I cannot login. (Android, iOS & macOS)

### ISSUE THREAD

**Issue by Hamachi-geek** [RocketChat/Rocket.Chat.ReactNative#4055]
### Description:
I cannot login to configured server after I clean install the app.
There is nothing to login displayed.

### Environment Information:

- Rocket.Chat Server Version: 4.6
- Rocket.Chat App Version: 4.26.1.14
- Device Name: 
  - Rakuten mini C330 
  - trueMoveH SMART4G 3.5 Hybrid
  - P-UP Mode-1 Grip MD-05P 
  - Samsung Galaxy S21 
  - Sharp AQUOS R2 compact 
  - Apple iPhone 13ProMax
  - Apple iPhone SE (2020)
  - Apple Mac mini (M1)
  
- OS Version: Android6.0, Android9, Android11, macOS12, iOS15

### Steps to reproduce:

1.  I installed Rocket.Chat client app to device.
2.  I started the app.
3.  I cannot any thing.

### Expected behavior:
I want to login to server which I would like to.

### Actual behavior:
But there's nothing to necessary.

![4533](https://user-images.githubusercontent.com/22436907/163361556-5022c405-f8a1-4b40-b107-bac4929e41fb.png)
![IMG_7768](https://user-images.githubusercontent.com/22436907/163361595-a135a513-3bfd-4dc8-92d9-74e9446aaf06.jpg)

### Additional context:
In case of the app has been update to 4.26.x after logged in with older version, this problem would not happened.

**Comment by diegolmello** [comment]
Hey, @Hamachi-geek.
Can you please try logging in https://open.rocket.chat?

**Comment by Hamachi-geek** [comment]
I could login to that and our server with 4.26.2 client app. (Which I installed from Google Play)

**Comment by Hamachi-geek** [comment]
I checked the bug was fixed in 4.26.2 . I appreciate for your work.

**Comment by jim0020** [comment]
Still having this problem. I'm using the iOS Simulator with an iPhone 13 on iOS 15.5.  I'm building single-server 52d56074 [IMPROVE] Disable Jitsi native module on Android (#4708).

 The fetch to {server}/api/info in lib/services.connect.ts never receives a response, resulting in a blank WorkspaceView.  I've tried this with both our chat server instance and https://open.rocket.chat.

The same code is working for me on Android emulator (Pixel 6 API 30).
