### ISSUE TITLE
After upgrading to 4.7.0 E2EE messages fail to show on IOS app

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat.ReactNative#4183]
![image](https://user-images.githubusercontent.com/93461213/167047794-f27a2f3a-9823-49fb-83d8-1986bb2c15dc.jpeg)

**Comment by cuongnn-smartosc** [comment]
Hi there, 
Any updates on this issue?
Thanks

**Comment by GleidsonDaniel** [comment]
> Hi there, Any updates on this issue? Thanks

It's in our pipe, but there are other priorities ahead.
We are open to PRs.

**Comment by antgel** [comment]
"Other priorities"? You completely broke the E2EE functionality in a release. As usual, there are too many regressions and existing users take a back seat, for shame.

**Comment by reinaldonetof** [comment]
Hi @lovekyleman , @cuongnn-smartosc, @antgel!
Sorry for you facing this problem. So, here are some questions for you:
1 - The problem was recognized after upgrading the Server to 4.7.0, or are you using another version of the server?
2 - The problem of decrypting is only for the mobile app, or is it occurring in the web app/desktop app?
3 - Did you recently reset the E2E key by the mobile app?
4 - Which is the version of the mobile app you are using?

While we are awaiting your answers, we started to research the fix for this critical problem. Later, we will bring some news and we are open to PRs.

**Comment by lovekyleman** [comment]
> Hi @lovekyleman , @cuongnn-smartosc, @antgel!
> 
> Sorry for you facing this problem. So, here are some questions for you:
> 
> 1 - The problem was recognized after upgrading the Server to 4.7.0, or are you using another version of the server?
> 
> 2 - The problem of decrypting is only for the mobile app, or is it occurring in the web app/desktop app?
> 
> 3 - Did you recently reset the E2E key by the mobile app?
> 
> 4 - Which is the version of the mobile app you are using?
> 
> 
> 
> While we are awaiting your answers, we started to research the fix for this critical problem. Later, we will bring some news and we are open to PRs.

1. after upgrading the Server to 4.7.0,4.8.0,4.8.1 the E2EE messages decrypting is broken ( E2EE messages before upgrading)
2.Mac app is okay.
decrypting is broken for the
mobile app
3. No E2E key reset 
4. Latest mobile app (IOS)

**Comment by MuRF2** [comment]
Any update?
The Android app version 4.33.1 is still experiencing the same issue. Whenever I update the server to versions 4.7 - 5.4, the problem occurs. Does anyone have a workaround for this issue?

Thanks in advance

**Comment by lovekyleman** [comment]
> Any update?
> 
> The Android app version 4.33.1 is still experiencing the same issue. Whenever I update the server to versions 4.7 - 5.4, the problem occurs. Does anyone have a workaround for this issue?
> 
> 
> 
> Only old messages are affected by this issue. New messages that are sent using the web client or the app are displayed correctly. The old messages are displayed correctly in the web client.
> 
> 
> 
> Thanks in advance
It's been long time ago. Seems no one cares about it.

**Comment by diegolmello** [comment]
Hey folks.

> Whenever I update the server to versions 4.7 - 5.4

That's new information. If true, for some reason the server update would break the e2e keys on mobile apps?
Can anybody else confirm?

I'm asking because we released a new version of the mobile app last week as well.
I've tried to reproduce this a few times, but I wasn't able.
Can you explain us the steps to do it?

Also resetting the E2E keys should work, since it's going to regenerate the keys on both clients.
Thanks!

**Comment by MuRF2** [comment]
I have installed the RocketChat server manually, following the instructions in your [documentation](https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/debian-based-distros/ubuntu). Both RocketChat and MongoDB are running on separate machines. Several channels and direct messages were encrypted with E2E from the start. The MongoDB database is from a previous installation using RocketChat snap package 3.x. Currently, I am using RocketChat 4.5.5 and MongoDB 5.0.  

The error is occurring with a self-compiled app based on the single server branch with exchanged assets. However, the app from the Play Store is also experiencing the same problem.

Here's what I've tried: 
Upgrade RocketChat server from version 4.5.5 to 4.8.6.
- Web client no issue. 
- Android app 4.29-4.33 cannot decrypt the old messages. From this point forward, new messages are not a problem and are displayed correctly.

For two accounts, the E2E encryption key was reset. 
- Web client no issue. 
- Android app cannot display old messages. No issue with new messages. 

When running the app in "debug mode" and entering a channel with "broken" messages, I get the following [output]( https://gist.github.com/MuRF2/f551e0167b8ad2cc16ad045dccf223f5 ). However, please forgive me if this is completely useless or incorrect, as I have no idea what I am doing. :D 

It would be helpful if someone else could perform a similar test to check my setup. Thanks in advance. And thanks for the quick reply @diegolmello @lovekyleman

**Comment by diegolmello** [comment]
Hey.

> I get the following [output](https://gist.github.com/MuRF2/f551e0167b8ad2cc16ad045dccf223f5).

Yeah, it's just an unrelated warning from React.

> It would be helpful if someone else could perform a similar test 

That would be amazing.

What I'm thinking here is why it would fail for old messages while working on new ones, but without changing any key.
And logging out or uninstalling the app doesn't solve the issue as well?

> The error is occurring with a self-compiled app based on the single server branch with exchanged assets. However, the app from the Play Store is also experiencing the same problem.

It's like if the user stops working on mobile apps after the server is updated?

**Comment by MuRF2** [comment]
I just realized that the android app version **4.28** correctly displays old messages after the RocketChat server was upgraded! (This time 4.5.5 to 5.4)

> And logging out or uninstalling the app doesn't solve the issue as well?

No, for Android Version 4.29-4.33 this does not help.

> It's like if the user stops working on mobile apps after the server is updated?

I don't know if I understand the question correctly (non-native English speaker). Anyway, after the server update, the android app can still be used normally and non-encrypted messages are displayed correctly. However, any existing E2E encrypted messages that were sent before the server update are no longer decrypted and cannot be viewed. New E2E encrypted messages that are sent after the update are displayed correctly.

**Comment by diegolmello** [comment]
We recently merged this and it could fix your issue https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763
We're going to release it in a few days.

Can you try and let us know if it works?
Thanks!

**Comment by lovekyleman** [comment]
5.4.2 Still not working. 
> We recently merged this and it could fix your issue https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763
> 
> We're going to release it in a few days.
> 
> 
> 
> Can you try and let us know if it works?
> 
> Thanks!

**Comment by diegolmello** [comment]
I didn't get.
We released 4.35.0 on mobile.
Server version is irrelevant.

**Comment by lovekyleman** [comment]
> I didn't get.
> 
> We released 4.35.0 on mobile.
> 
> Server version is irrelevant.

I'm using 4.35.0 iOS app now. Still can't read old messages.
Anyway. Maybe old messages are not important. 
Never mind 
Thanks for your time
