### ISSUE TITLE
Chat images and user avatars disappear if two side TLS is used in the android client

### ISSUE THREAD

**Issue by alarkip** [RocketChat/Rocket.Chat.ReactNative#4192]
### Description:

Chat images and user avatars disappear if two side TLS is used in the android client

### Environment Information:

Android 11
Rocket.Chat.Android 4.27.0.31976
Rocket.Chat Server 4.5.1
The Rocket.Chat server is behind another server (Nginx + OpenSSL) that provides TLS authentication with a client certificate

1. Install on android certificate certificate with private key for client authentication
2. Connect to the RocketChat server using this certificate

The connection is made, the chat works, but user avatars periodically disappear, and transferred images in chats stop loading.
Temporarily fixed with Settings - Clear local server cache.
When working without TLS authentication, this does not happen.

I can provide a ready test stand.

**Comment by rmaksimov** [comment]
I have the same issue on Android 10. RocketChat client version is 4.27.1, server version is 4.7.1

**Comment by Sx3** [comment]
Same issue with IOS Client 4.29 and server version 4x

**Comment by diegolmello** [comment]
We fixed request challenges on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4826
It could fix it.
We're going to make the release in a few days.
We can reopen the issue if needed.
Thanks!

**Comment by alarkip** [comment]
There is still a bug in version 4.35.1.37443 for android

**Comment by rmaksimov** [comment]
I can confirm, the bug still persists
Android: 12skq1.211006.001
RC client: 4.35.1.37443
RC server: 5.4.2

**Comment by rmaksimov** [comment]
Is there any news on this issue, guys?

**Comment by diegolmello** [comment]
Fixed on a recent release.
