### ISSUE TITLE
RocketChat Client on iPadOS 17.x hangs and crashes when typing from Magic Keyboard.

### ISSUE THREAD

**Issue by fc757** [RocketChat/Rocket.Chat.ReactNative#5260]
### Description:

RocketChat Client on iPadOS 17.x hangs and crashes when typing from Magic Keyboard.

### Environment Information:

- Rocket.Chat Server Version:  6.4.0
- Rocket.Chat App Version: 4.41.0.49562 and previous 
- Device Name: iPad Pro 12.9 3rd Generation
- OS Version: iPadOS 17.0.3

### Steps to reproduce:

1. Click on channel
2. Click in new message field 

### Expected behavior:

Being able to type in new message field.

### Actual behavior:

App freezes and needs to be quit and relaunch

### Additional context:

Oddly enough, if you click on the emoji icon and then click on the new message field, it works and you can type. But you have to do that every time or else it crashes. 

If device is disconnected from Magic Keyboard and you use touch screen for typing, app works as expected.

**Comment by fc757** [comment]
If I go into Accessibility - > Touch -> AssistiveTouch and turn on AssistiveTouch, when I go into RocketChat I am able to click in the enter message field and type a message. The onscreen keyboard pops up when I do this.

**Comment by Steve1516RLF** [comment]
Exactly same problem on iOS 17.0.3, iPhone SE 2020.
SwiftKey keyboard.

**Comment by dsjiern** [comment]
Same problem here, App Version: 4.42.0, iPad Pro (iOS 17.1) with Magic Keyboard.
But no problem on iPhone with SwiftKey.

**Comment by maiksd** [comment]
Same here. App accepts no input on Magic Keyboard, seems to go into an infinite loop and consume all memory until it crashes and even takes the whole springboard with it. I'm attaching crash logs.
[rcrashlogs.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/13241983/rcrashlogs.zip)

**Comment by fc757** [comment]
So, after a while of struggling. I managed to compile the iOS RocketChat client on my M1 Mac Mini. When I click on the message input field with my Magic Keyboard on my iPad, the following shows up in the XCode console, maybe it can help shed some light on this issue:

Task <A38B96B1-2341-45D4-BC69-03192DB51A34>.<33> HTTP load failed, 0/0 bytes (error code: 18,446,744,073,709,550,611 [1:57])

-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID

CGImageSourceCreateImageAtIndex:4450: *** ERROR: CGImageSourceCreateImageAtIndex[0] - '....' - failed to create image

**Comment by LolYangccool** [comment]
Same problem here with an iPad Pro on iPadOS 17.1.1 and Rocket.chat last version at this time.

**Comment by xilni** [comment]
Same issue.
iPad Pro w Magic Keyboard
iOS 17.1.1
Rocket.chat 4.42.2.51088
Workspace version 6.4.0

**Comment by diegolmello** [comment]
There seems to be an issue with iOS 17. Some apps are super slow to type on my iPhone as well.
https://discussions.apple.com/thread/255165111
https://www.reddit.com/r/ios/comments/16mm782/ios_17_keyboard_lag/

**Comment by Donngd** [comment]
Yes, the problem has been resolved on my end with iPadOS 17.0.3. Currently, connecting MagicKeyboard will show an accessory incompatible prompt, but rocket.chat usage is normal.
https://github.com/RocketChat/Rocket.Chat/issues/30451#issuecomment-1749022339

**Comment by fc757** [comment]
So, I was still on the beta installs for my iPad and iPadOS 7.2 was installed and the Magic keyboard still crashed. Saw the posts about 17.0.3 and did a restore on my iPad and iPadOS 7.1.1 was installed and my Magic keyboard is not working properly in RocketChat with no crashes. \o/

**Comment by fc757** [comment]
> Same issue. iPad Pro w Magic Keyboard iOS 17.1.1 Rocket.chat 4.42.2.51088 Workspace version 6.4.0

So, I saw this and was trying to figure out why my Magic Keyboard is working with 17.1.1 and yours is not. If I disable Predictive in Settings->General->Keyboards my RocketChat will crash with the Magic Keyboard. If Predictive is enabled, it seems fine. Issue still not totally ironed out it seems. I wonder if that was the issue the whole time for me.

**Comment by maiksd** [comment]
Interesting, but that doesn't make a difference in my case. Still crashes every time, at least with the Folio keyboard I have with me now, with or without Predictive.

**Comment by fc757** [comment]
> Interesting, but that doesn't make a difference in my case. Still crashes every time, at least with the Folio keyboard I have with me now, with or without Predictive.

The only other thing I did was a restore to iPadOS 17.1.1 and blew out all my stuff. Bit extreme, but this app is what I mostly use on this iPad. 

Now that the keyboard is working, enter doesn't work to send a message. I have to click the blue airplane send icon to send a message. Kinda annoying. I had this bug in the past, but it was fixed somewhere down the road. Hopefully all this gets straightened out soon. 

Or maybe I should just give up on this app and use the webpage instead, everything tends to work better there, just doesn't get notifications and the menu bar in safari wastes screen space, but you can hide that, just have to do it every time. There is probably a full screen webpage app for iPadOS.

**Comment by diegolmello** [comment]
We sent https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5343 to review on App Store.
It's going to be released as soon as it's approved by Apple on 4.43.0, which can take a day or two.
I'll let you know once it's published, so you can try on your devices and check if the issue is fixed.
Thanks!

**Comment by maiksd** [comment]
Just installed the update and can confirm the issue is fixed. In fact, I'm typing this on the Magic Keyboard on my iPad. Thanks!

**Comment by LolYangccool** [comment]
This update works fine for me too, with the Magic Keyboard on my iPad Pro M2. :)
Thanks you.

**Comment by Steve1516RLF** [comment]
Rocket.Chat version 4.43.0.52294 in iOS version 17.1.1 on iPhone SE (2020) works now flawlessly with SwiftKey. Thanks.

**Comment by diegolmello** [comment]
Awesome, folks!
Thanks for the feedback.
Closing 🤙🏼
