### ISSUE TITLE
Users are logged out of the app every time they close it on their new iPhones.

### ISSUE THREAD

**Issue by david-uhlig** [RocketChat/Rocket.Chat.ReactNative#6011]
### Description:

Users are being logged out of the Rocket.Chat app every time they close it on their new iPhones.

This issue specifically affects users who have recently switched to new devices. They were able to stay logged in on our self-hosted Rocket.Chat instance without any problems on their previous devices. Now, after they successfully logged in to the instance, then close the app - without logging out, explicitly - they have to log in again when they open it up the next time. Since they are not logged in, they also don't receive any push notifications.

We tried without success
* Explicitly logging out of the account on the old device

The app permissions are identical on both devices.

### Environment Information:

- Rocket.Chat Server Version: 6.13.0
- Rocket.Chat App Version: 4.54.1.68xxx
- Device Name: iPhone
- OS Version: 

### Steps to reproduce:

1. Create a new user account with a iPhone device.
2. Sign in
3. Close the app
4. Reopen the app
5. Confirm you're still logged in
6. On a different iPhone device, possibly a recent one:
7. Sign in
8. Close the app
9. Reopen the app
10. You should land on the sign in page again

### Expected behavior:

The user should stay logged in unless they explicitly log out.

### Actual behavior:

They have to log in every time they open the app.

**Comment by diegolmello** [comment]
> We tried without success
> Explicitly logging out of the account on the old device

Can you try logging out and logging in on the new device?

**Comment by Lao-Ax** [comment]
We got the same behaviour with our users. But still cannot repruduce on dev env. Re-insalling the app helped for those poor users. But it helps not always. Last time a user had to logout from every session on other places (desktop\web and other devices).

If I find anything - I will share it in this topic.

**Comment by david-uhlig** [comment]
> > We tried without success
> > Explicitly logging out of the account on the old device
> 
> Can you try logging out and logging in on the new device?

We did, and this worked for one of our users. I assume it works for the others, too, but I have no confirmation from them.

**Comment by StefanKoell** [comment]
I see the same issue. Tried everything (re-install, log off all sessions, etc.). When the app is closed (manually by user or cleaned up by the system), I have to re-login. 

Not sure if it's related but if I click on a notification (on the lock screen), rocket.chat opens but I'm also logged out and have to re-login. 

My instance requires an MFA code (delivered by email) which makes the whole process super annoying.

**Comment by iTitus** [comment]
I had the same issue after I switched to a new device. Completely reinstalling the app fixed it for me.

**Comment by devTomek** [comment]
It is happening to me when I want to open rocket through notification. 

iPhone 15
iOS 18.4.1

**Comment by david-uhlig** [comment]
Just had another user reporting this issue on a new iPhone. We were able to solve it:

1. Manually logging out of the app on the new phone -> no success
2. Admin reset TOTP token; none was set
3. User uninstalled and reinstalled the Rocket Chat app -> success

**Comment by Gummikavalier** [comment]
In our recent user case with migratated to new iPhone RC app issue was fixed after following these steps:

1. Resetting TOTP by admin for the user (even if it was not used)
2. Login to RC app (if you are not currently logged into it)
3. Top left menu -> Settings -> At the bottom: `Clear local workspace cache`
4. Same spot: `Logout`
5. Uninstall the app completely
6. Reinstall the RC app from AppStore
7. And finally log back into the RC app

So there is at least some chance that the issue may get fixed by resetting TOTP for the user (even if unused).

We did try just plain reinstall before trying with the above steps, and it didn't work. On this I have to trust the user's word.

If we hit this again, it is probably best to try with exact three steps in @david-uhlig 's comment, or perhaps just with TOTP reset and relogin.

**Comment by pke** [comment]
Not using TOTP but the issue is still there. Not for all users of the workspace though. Re-installing the app does not fix it.

**Comment by Gummikavalier** [comment]
@pke Our users who had issues did not use TOTP either, but TOTP reset for them may be a mandatory step to fix the issue. Try also all of the other above steps in order.

**Comment by pmb0** [comment]
I was able to solve the problem as follows: log in on the new iPhone, then go to your profile, then press “log out on other logged-in devices.”
